### ISSUE TITLE
incompatible with black v22.1.0 ?

### ISSUE THREAD

**Issue by jedie** [akaihola/darker#264]
```
$ poetry run darker .
Traceback (most recent call last):
  File "/home/jens/repos/dev-shell/.venv/bin/darker", line 8, in <module>
    sys.exit(main_with_error_handling())
  File "/home/jens/repos/dev-shell/.venv/lib/python3.9/site-packages/darker/__main__.py", line 421, in main_with_error_handling
    return main()
  File "/home/jens/repos/dev-shell/.venv/lib/python3.9/site-packages/darker/__main__.py", line 312, in main
    args, config, config_nondefault = parse_command_line(argv)
  File "/home/jens/repos/dev-shell/.venv/lib/python3.9/site-packages/darker/command_line.py", line 107, in parse_command_line
    config = load_config(args.src)
  File "/home/jens/repos/dev-shell/.venv/lib/python3.9/site-packages/darker/config.py", line 107, in load_config
    path = find_project_root(tuple(srcs or ["."])) / "pyproject.toml"
TypeError: unsupported operand type(s) for /: 'tuple' and 'str'
```

black changed the return value of find_project_root() here: https://github.com/psf/black/commit/521d1b8129c2d83b4ab49270fe7473802259c2a2#diff-1a5882c84fe4b3f18199a3e021822c1ea4bdc3f86952ea450c4db15d9387c7c3

It's not a tuple :(

**Comment by foxwhite25** [comment]
Can comfirm with my project action
```
Run akaihola/darker@github-action-v1.3.2-2
Run # Exists since using github.action_path + path to main script doesn't work
Traceback (most recent call last):
  File "/home/runner/work/_actions/akaihola/darker/github-action-v1.3.2-2/.darker-env/bin/darker", line 8, in <module>
    sys.exit(main_with_error_handling())
  File "/home/runner/work/_actions/akaihola/darker/github-action-v1.3.2-2/.darker-env/lib/python3.8/site-packages/darker/__main__.py", line 421, in main_with_error_handling
    return main()
  File "/home/runner/work/_actions/akaihola/darker/github-action-v1.3.2-2/.darker-env/lib/python3.8/site-packages/darker/__main__.py", line 312, in main
    args, config, config_nondefault = parse_command_line(argv)
  File "/home/runner/work/_actions/akaihola/darker/github-action-v1.3.2-2/.darker-env/lib/python3.8/site-packages/darker/command_line.py", line 107, in parse_command_line
    config = load_config(args.src)
  File "/home/runner/work/_actions/akaihola/darker/github-action-v1.3.2-2/.darker-env/lib/python3.8/site-packages/darker/config.py", line 107, in load_config
    path = find_project_root(tuple(srcs or ["."])) / "pyproject.toml"
TypeError: unsupported operand type(s) for /: 'tuple' and 'str'
Error: Process completed with exit code 1.
```

**Comment by akaihola** [comment]
This will be fixed in #270.

**Comment by mayk0gan** [comment]
is there some workaround in the meanwhile?
I use darker's github action from the master branch (as suggested [here](https://github.com/akaihola/darker/issues/253)

**Comment by jedie** [comment]
I just pin black as a work-a-round:
```
darker = "*"
black = "==21.12b0"
```

**Comment by mayk0gan** [comment]
> I just pin black as a work-a-round:
> 
> ```
> darker = "*"
> black = "==21.12b0"
> ```

I'm not sure that it would work with the github action. Do you put it in `pyproject.yaml`?

**Comment by mayk0gan** [comment]
The github action still doesn't work on master though:

```code
Traceback (most recent call last):
  File "/home/runner/work/_actions/akaihola/darker/master/.darker-env/bin/darker", line 8, in <module>
    sys.exit(main_with_error_handling())
  File "/home/runner/work/_actions/akaihola/darker/master/.darker-env/lib/python3.8/site-packages/darker/__main__.py", line [42](https://github.com/sentraio/sentra-discovery/runs/5085406006?check_suite_focus=true#step:4:42)1, in main_with_error_handling
    return main()
  File "/home/runner/work/_actions/akaihola/darker/master/.darker-env/lib/python3.8/site-packages/darker/__main__.py", line 312, in main
    args, config, config_nondefault = parse_command_line(argv)
  File "/home/runner/work/_actions/akaihola/darker/master/.darker-env/lib/python3.8/site-packages/darker/command_line.py", line 107, in parse_command_line
    config = load_config(args.src)
  File "/home/runner/work/_actions/akaihola/darker/master/.darker-env/lib/python3.8/site-packages/darker/config.py", line 107, in load_config
    path = find_project_root(tuple(srcs or ["."])) / "pyproject.toml"
TypeError: unsupported operand type(s) for /: 'tuple' and 'str'
Error: Process completed with exit code 1.
```

**Comment by akaihola** [comment]
@mayk0gan I think it still clones the last release when building the image even though the action "recipe" comes from `master`. Should be fixed when we release 1.4.0.

**Comment by foxwhite25** [comment]
It still failed with a @1.4.0 to specify 1.4.0, thats odd.
`Run akaihola/darker@1.4.0
Run # Exists since using github.action_path + path to main script doesn't work
Traceback (most recent call last):
  File "/home/runner/work/_actions/akaihola/darker/1.4.0/.darker-env/bin/darker", line 8, in <module>
    sys.exit(main_with_error_handling())
  File "/home/runner/work/_actions/akaihola/darker/1.4.0/.darker-env/lib/python3.8/site-packages/darker/__main__.py", line [42](https://github.com/foxwhite25/qq.py/runs/5121125995?check_suite_focus=true#step:3:42)1, in main_with_error_handling
    return main()
  File "/home/runner/work/_actions/akaihola/darker/1.4.0/.darker-env/lib/python3.8/site-packages/darker/__main__.py", line 312, in main
    args, config, config_nondefault = parse_command_line(argv)
  File "/home/runner/work/_actions/akaihola/darker/1.4.0/.darker-env/lib/python3.8/site-packages/darker/command_line.py", line 107, in parse_command_line
    config = load_config(args.src)
  File "/home/runner/work/_actions/akaihola/darker/1.4.0/.darker-env/lib/python3.8/site-packages/darker/config.py", line 107, in load_config
    path = find_project_root(tuple(srcs or ["."])) / "pyproject.toml"
TypeError: unsupported operand type(s) for /: 'tuple' and 'str'
Error: Process completed with exit code 1.`

**Comment by jenshnielsen** [comment]
@foxwhite25 the action has a version setting that defaults to 1.3.2 you probably need to explicitly set that to 1.4.0 https://github.com/akaihola/darker/blob/master/action.yml#L18

**Comment by akaihola** [comment]
Thanks @mayk0gan @foxwhite25 @jenshnielsen, I'll look into this soon. Is this the same as #260?

**Comment by jenshnielsen** [comment]
I have set it with the following config which seems to work fine.
But note that I need to set the version twice

‘’’
name: Lint with Darker

 on: [push, pull_request]

 jobs:
   lint-with-darker:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - uses: akaihola/darker@1.4.0
         with:
           options: "--check --diff -r origin/master -i"
           version: "1.4.0"

‘’’

**Comment by MatthijsBurgh** [comment]
As mentioned in @260. The action file still sets `1.3.2` as the darker version to be used. Even in master and the `1.4.0` tag. So a manual override is still needed at the moment. But this should be fixed in the action file.

**Comment by jedie** [comment]
I made this:

https://github.com/boxine/django-huey-monitor/blob/49d5b214afa1f0af0b8e7fb9b24f92327c8ad5be/.github/workflows/pythonapp.yml#L24-L29

to always compare with master ;)

**Comment by jenshnielsen** [comment]
@jedie I originally started with ``--check --diff -r master`` but realized that using ``--check --diff -r origin/master`` I did not need to explicitly fetch the master branch

**Comment by jedie** [comment]
Hm. Interesting: I use `revision = "origin/master..."` in `pyproject.toml`: https://github.com/boxine/django-huey-monitor/blob/49d5b214afa1f0af0b8e7fb9b24f92327c8ad5be/pyproject.toml#L74

Think the fetch is needed. But let's try this: https://github.com/boxine/django-huey-monitor/pull/85 https://github.com/boxine/django-huey-monitor/actions/runs/1828419972
